name = "prompt-template"
main = "src/index.ts"
compatibility_date = "2025-05-13"

assets = { directory = "public" }

[[d1_databases]]
binding = "DB"
database_name = "prompt-template-db"
database_id = "60c12bd2-1beb-4a0d-85f9-6cb5b2dc9ddc"

